package com.hasitha.int20220405.models;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Quote {
    private String language;
    private String region;
    private String quoteType;
    private String typeDisp;
    private String quoteSourceName;
    private boolean triggerable;
    private String customPriceAlertConfidence;
    private String currency;
    private String exchange;
    private String shortName;
    private String longName;
    private String messageBoardId;
    private String exchangeTimezoneName;
    private String exchangeTimezoneShortName;
    private int gmtOffSetMilliseconds;
    private String market;
    private boolean esgPopulated;
    private long firstTradeDateMilliseconds;
    private int priceHint;
    private double preMarketChange;
    private double preMarketChangePercent;
    private int preMarketTime;
    private double preMarketPrice;
    private double regularMarketChange;
    private double regularMarketChangePercent;
    private int regularMarketTime;
    private double regularMarketPrice;
    private double regularMarketDayHigh;
    private String regularMarketDayRange;
    private double regularMarketDayLow;
    private int regularMarketVolume;
    private double regularMarketPreviousClose;
    private int bid;
    private int ask;
    private int bidSize;
    private int askSize;
    private String fullExchangeName;
    private String financialCurrency;
    private double regularMarketOpen;
    private int averageDailyVolume3Month;
    private int averageDailyVolume10Day;
    private double fiftyTwoWeekLowChange;
    private double fiftyTwoWeekLowChangePercent;
    private String fiftyTwoWeekRange;
    private double fiftyTwoWeekHighChange;
    private double fiftyTwoWeekHighChangePercent;
    private double fiftyTwoWeekLow;
    private double fiftyTwoWeekHigh;
    private int dividendDate;
    private int earningsTimestamp;
    private int earningsTimestampStart;
    private int earningsTimestampEnd;
    private double trailingAnnualDividendRate;
    private double trailingPE;
    private double trailingAnnualDividendYield;
    private double epsTrailingTwelveMonths;
    private double epsForward;
    private double epsCurrentYear;
    private double priceEpsCurrentYear;
    private long sharesOutstanding;
    private double bookValue;
    private double fiftyDayAverage;
    private double fiftyDayAverageChange;
    private double fiftyDayAverageChangePercent;
    private double twoHundredDayAverage;
    private double twoHundredDayAverageChange;
    private double twoHundredDayAverageChangePercent;
    private long marketCap;
    private double forwardPE;
    private double priceToBook;
    private int sourceInterval;
    private int exchangeDataDelayedBy;
    private double pageViewGrowthWeekly;
    private String averageAnalystRating;
    private boolean tradeable;
    private String marketState;
    private String displayName;
    private String symbol;
}
